resourcestring                                     {english}

{Column header data}
  hdParamter='Parameter';
  hdValue='Wert';
  hdDistance='Abstand';      {Distance between waypoints}
  hdAscent='Delta';          {Delta altitude between waypoints (ascent/descent}
  hdAddtrkpt='Zus. trkpt';   {Number additional trackpoints between Waypoints}

{Controls}
  capOpen='&Öffnen';
  hntOpen='Anafi Flugplan JSON Datei öffnen und verarbeiten.';
  capClose='&Beenden';
  hntClose='Programm schließen';
  hntMetaGrid='Metadaten aus dem Flugplan';
  hntPOIgrid='Verschiedene Punkte  aus dem Flugplan';
  hntWPgrid='Liste der Waypoints aus dem Flugplan';
  capTrkpt='Zus. trackpoints';
  hntTrkpt='Zusätzliche trackpiots zwischen den Wayppoints einfügen (linear interpoliert)';
  capRate='Rate der zusätzlichen TRKPT';
  hntRate='Rate  Trackpoints (geringere Werte bedeuten mehr Punkte)';

  rsContact='Kontakt';
