resourcestring                                     {english}

  {Column header data}
    hdParamter='Parameter';
    hdValue='Value';
    hdDistance='Distance';     {Distance between waypoints}
    hdAscent='Delta';          {Delta altitude between waypoints (ascent/descent}
    hdAddtrkpt='Add. trkpt';   {Number additional trackpoints between Waypoints}

  {Controls}
    capOpen='&Open';
    hntOpen='Open and process Anafi flight plan JSON file.';
    capClose='&Close';
    hntClose='Close application.';
    hntMetaGrid='Meta data from flight plan';
    hntPOIgrid='Multiple points from flight plan';
    hntWPgrid='List of waypoints from flight plan';
    capTrkpt='Add. trackpoints';
    hntTrkpt='Create additional trackpiots between the waypoints (linear interpolated)';
    capRate='Rate of additional trkpt';
    hntRate='Rate of additional trackpoints (less rate means more points)';

    rsContact='Contact';


